run:
  timeout: 5m
  go: "1.21"

linters:
  enable:
    - gofmt
    - goimports
    - golint
    - govet
    - ineffassign
    - misspell
    - errcheck
    - staticcheck
    - unused
    - gosec
    - gocyclo

linters-settings:
  gocyclo:
    min-complexity: 10
  golint:
    min-confidence: 0.8

issues:
  exclude-use-default: false
  max-same-issues: 50

