apiVersion: apps/v1
kind: Deployment
metadata:
  name: modernblog-frontend
  namespace: modernblog-dev
  labels:
    app: modernblog-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modernblog-frontend
  template:
    metadata:
      labels:
        app: modernblog-frontend
    spec:
      containers:
      - name: frontend
        image: modernblog-frontend
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "http://localhost:8080"
        - name: NODE_ENV
          value: "development"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: modernblog-frontend
  namespace: modernblog-dev
  labels:
    app: modernblog-frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
    protocol: TCP
  selector:
    app: modernblog-frontend