kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: modernblog-cluster

nodes:
  # Control plane node with ingress
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 8080
        protocol: TCP
      - containerPort: 443
        hostPort: 8443
        protocol: TCP

  # Worker node 1
  - role: worker

  # Worker node 2  
  - role: worker