apiVersion: skaffold/v4beta9
kind: Config

build:
  local:
    push: false
  artifacts:
    - image: modernblog-api
      context: backend
      docker:
        dockerfile: Dockerfile
    - image: modernblog-web
      context: frontend
      docker:
        dockerfile: Dockerfile

manifests:
  rawYaml:
    - dev/postgres.yaml

deploy:
  kubectl:
    defaultNamespace: modernblog

portForward:
  - resourceType: service
    resourceName: postgres
    port: 5432
    localPort: 5432