apiVersion: skaffold/v4beta9
kind: Config

build:
  local:
    push: false
  artifacts:
    - image: modernblog-api
      context: backend
      docker:
        dockerfile: Dockerfile
    - image: modernblog-web
      context: frontend
      docker:
        dockerfile: Dockerfile

deploy:
  kubectl:
    manifests:
      - k8s/*.yaml